workflows:
  build-android:
    name: Build Android
    environment:
      groups:
        - keystore
        - all
      flutter: 3.22.0
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Analyze
        script: flutter analyze
      # - name: Run test
      #   script: flutter test test/
      - name: Build
        script: |
          echo "Publish onePubdev"
          onepub login"
          onepub export --user muhajirilarobbih@gmail.com"
          export PATH='$PATH:/home/.pub-cache/bin' -- this is probably not correct"
          dart pub global activate onepub"
          export ONEPUB_TOKEN="MzMxODo5MmRhYzg1NS0zZjNlLTQ3OWQtYmVkNC1iZjBmNzhlODI4OWY=";onepub import"
      
